[package]
name = "rust_get_card"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]


[dependencies]
ludndev-hello-world = "0.1.1"

